[package]
name = "cube-lib"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "2"

[dev-dependencies]
itertools = "0.14.0"
proptest = "1.7.0"
proptest-derive = "0.8.0"
